### ISSUE TITLE
Arama Kısmında Sure Numaralarının Yanında Sure Adlarının Yazmaması

### ISSUE THREAD

**Issue by yusufbalyemez** [yunusem/quran-tft#26]
Search kısmında sure numaralarının yanında sure adları da gözükmeli

![Screen Shot 2 01 2024 at 12 46](https://github.com/yunusem/quran-tft/assets/124602727/5014ca4a-ce03-4661-9f07-bba261fd3693)

**Comment by yunusem** [comment]
It shows the name on the middle pane, so I probably won't implement this at all. When jumping to a specific sura, the navigation should not depend on its name because it is translatable, and the interactive book (QURANTFT) forces the user to pay attention to the meaning of the header (Why GOD named that sura with that name) so that it conflicts with the comprehension of the idea and with how a human brain is working.
